
import path from "node:path";

// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

function resolveDatasourceUrl(databaseUrl: string) {
  if (!databaseUrl.startsWith("file:./")) {
    return databaseUrl;
  }

  const relativePath = databaseUrl.slice("file:".length);
  return `file:${path.resolve(process.cwd(), relativePath)}`;
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    url: resolveDatasourceUrl(env("DATABASE_URL")),
  },
});
